### ISSUE TITLE
Use Flask-DebugToolbar

### ISSUE THREAD

**Issue by jeffwidman** [cburmeister/flask-bones#27]
Using Flask-DebugToolbar adds a number of helpful things, including timing pageloads (without having to manually code it) and viewing SQLAlchemy queries.

**Comment by cburmeister** [comment]
Are you planning on helping out with the majority of these issues?

**Comment by jeffwidman** [comment]
More than happy to help with PRs, just wasn't sure what changes you were open to... you open to this?
