### ISSUE TITLE
cachecore isn't available on pypi

### ISSUE THREAD

**Issue by jeffwidman** [cburmeister/flask-bones#31]
https://pypi.python.org/pypi/cachecore/ is 404'ing for me

**Comment by cburmeister** [comment]
Maybe it should be replaced with https://pythonhosted.org/Flask-Cache/

**Comment by jeffwidman** [comment]
I've [read good things](http://brunorocha.org/python/flask/using-flask-cache.html) about Flask-Cache, but haven't personally played with it.

**Comment by kampta** [comment]
Anyone working on this?

**Comment by cburmeister** [comment]
Nope but feel free @kampta !

**Comment by kampta** [comment]
Tried and got stuck with quite a number of packages being outdated (amqp, billiard, celery, kombu not in order) :( Will try again with more free time

**Comment by seanieb** [comment]
I added a simple fix in this pull request to fix this.

**Comment by kampta** [comment]
:+1: 

Thanks @seanieb.

I had a doubt. Don't think it's related to cachecore (and might be something very trivial I am missing) but whenever I do 
```
docker-compose up
```

two of the containers don't start saying
```
celery_1       | make: *** No rule to make target 'celery'.  Stop.
app_1          | make: *** No rule to make target 'server'.  Stop.
```

**Comment by seanieb** [comment]
If you run this:
`docker logs app_1`
It will give you the log for that server and give us some insight into whats going wrong.

**Comment by kampta** [comment]
Tried that command already, that's the only thing the logs say

```
make: *** No rule to make target 'server'.  Stop.
```
