### ISSUE TITLE
User_accessed is invalid

### ISSUE THREAD

**Issue by syncml** [cburmeister/flask-bones#48]
Hi
  I'm using this scaffold to build my project. When I add user_access func to record user access time. but seem to it 's invalid . What is the problem? 
thank you

auth/view.py
```
from flask_login import (current_user, login_required, user_accessed,
                         logout_user, UserMixin, AnonymousUserMixin,
                         confirm_login, login_user)
...
@user_accessed.connect_via(auth)
def when_user_accessed(sender, **extra):
    user_id = session.get('user_id')
    if user_id:
        print 'access'

...
```

**Comment by cburmeister** [comment]
Hi,

This isn't a `flask-bones` issue -- I would ask in the  [flask-login issue tracker](https://github.com/maxcountryman/flask-login).
