### ISSUE TITLE
Unuseably slow

### ISSUE THREAD

**Issue by mattouille** [cburmeister/flask-bones#49]
I've been trying to get this to work for the better part of a day and it just appears to be unuseably slow. I even stripped out the database portion.

Any ideas on what'd be slowing this down?

EDIT: I also stripped out REDIS and the problem persists.

**Comment by cburmeister** [comment]
@mattouille my experience with this on a few different platforms is nice and speedy.

What is slow? Want to provide some more details about your environment?
